plugins:
  discourse_event_system_enabled:
    default: true
    client: true
  discourse_event_system_paypal_client_id:
    default: ""
    client: true
  discourse_event_system_paypal_secret:
    default: ""
    client: false
  discourse_event_system_paypal_sandbox:
    default: true
    client: true
  discourse_event_system_category_name:
    default: "RC Meetings"
    client: true
  discourse_event_system_category_slug:
    default: "rc-meetings"
    client: true